DROP TABLE IF EXISTS participation_requests;


CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP    NOT NULL,
    event_id     BIGINT,
    requester_id BIGINT,
    status       VARCHAR(100) NOT NULL
);