spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**,/internal/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: FallbackController
                fallbackUri: forward:/fallback

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/internal/comments/**,/users/*/comments/**
          filters:
            - name: CircuitBreaker
              args:
                name: FallbackController
                fallbackUri: forward:/fallback

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**,/internal/request/**
          filters:
            - name: CircuitBreaker
              args:
                name: FallbackController
                fallbackUri: forward:/fallback

        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/internal/categories/**
          filters:
            - name: CircuitBreaker
              args:
                name: FallbackController
                fallbackUri: forward:/fallback

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/internal/events/**,/users/*/events/**,/events/**,/admin/compilations/**,/compilations/**,/internal/compilations/**
          filters:
            - name: CircuitBreaker
              args:
                name: FallbackController
                fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

server:
  port: 8080