spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/stats
    username: stats
    password: stats

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: stats_analyzer
  sql:
    init:
      mode: always

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    user-actions-group-id: analyzer-user-actions
    events-similarity-group-id: analyzer-events-similarity
    poll-timeout-ms: 500
    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1


grpc:
  server:
    port: 0