server:
  port: 0

grpc:
  server:
    port: -1
  client:
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/event
    username: event
    password: event
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always